apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-dist
spec:
  replicas: 8
  selector:
    matchLabels:
      app: conv-dist
  template:
    metadata:
      labels:
        app: conv-dist
    spec:
      containers:
        - name: conv-dist
          image: aloysioc/conv-dist:v2
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: conv-dist
spec:
  selector:
    app: conv-dist
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30000
  type: NodePort